[parameters]
params = [
    [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [8, 16, 24, 32],
       [8, 16, 24, 32],
       [16, 32, 1024, 2048],
       [16, 32, 1024, 2048],
]

[config]
n_way = 4
seeds = [
    [3, 3, 1, 0, 0, 0, 0, 32, 32, 1024, 1024]
]
